---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "6"  
spec:
  version: 7.5.0
  count: 1
  elasticsearchRef:
    name: {{  .Values.elasticsearchRefName  }}
