{{- if .Values.aws.enableStorage }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-grafana
provisioner: efs.csi.aws.com
parameters:
  fileSystemId: {{  .Values.aws.efs.fileSystemId }}
  accessPointId: {{  .Values.aws.efs.accessPointId }}
  directoryPerms: "777"
  uid: "1000"
  gid: "1000"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  annotations:
    elasticsearch.k8s.elastic.co/csi-driver: efs.csi.aws.com 

spec:
  capacity:
    storage: {{  .Values.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-grafana
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{  .Values.aws.efs.fileSystemId }}

{{- end }}     