---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [ "" ]
  resources: [ "pods", "services","nodes","namespace","persistentvolumeclaims"]
  verbs: [ "get", "list", "watch","create", "update", "patch", "delete"]
- apiGroups: [ "extensions" ]
  resources: [ "deployments" ]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [ "jaegertracing.io" ]
  resources: [ "jaegers" ] 
  verbs: [ "delete", "create" ,"get", "list", "patch", "update", "watch"]
- apiGroups: [ "opentelemetry.io" ]
  resources: [ "opentelemetrycollectors" ]
  verbs: [ "get" ,"list" ,"patch" ,"update" ,"watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pod-reader
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: default