apiVersion: v1
kind: ConfigMap
metadata:
  name: ws-chart-config
  namespace: default

data:
  jaeger_endpoint: {{  .Values.jaegerEndpoint }}
  elasticsearch_secret: {{  .Values.elasticsearchSecretName }}
  elasticsearch_name: {{  .Values.elasticsearchName }}
  elasticsearch-secret: {{  .Values.elasticsearchSecretName }}
  elasticsearch-name: {{  .Values.elasticsearchName }}
  otel_name: {{  .Values.otelName }}
