apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rus-basic-cluster
  region: ap-south-1
      
nodeGroups:
  - name: ng-1
    instanceType: t2.xlarge
    desiredCapacity: 1
    volumeSize: 16
    ssh:
      allow: true 
