annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Updated Fluent Bit image to v2.0.9."
apiVersion: v1
appVersion: 2.0.9
description: Fast and lightweight log processor and forwarder or Linux, OSX and BSD
  family operating systems.
home: https://fluentbit.io/
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/fluentd/fluentbit/icon/fluentbit-icon-color.svg
keywords:
- logging
- fluent-bit
- fluentd
maintainers:
- email: eduardo@calyptia.com
  name: edsiper
- email: naseem@transit.app
  name: naseemkullah
- email: towmeykaw@gmail.com
  name: Towmeykaw
- email: steve.hipwell@gmail.com
  name: stevehipwell
name: fluent-bit
sources:
- https://github.com/fluent/fluent-bit/
version: 0.24.0
dependencies:
  - name: eck-kibana
    version: "0.2.0"
    repository: "file://../eck-kibana"
  - name: opentelemetry-operator
    version: "0.23.0"
    repository: "file://../opentelemetry-operator"
  # - name: jaeger
  #   version: "0.1.0"
  #   repository: "file://../jaeger"        

