applicationName: eks-fargate-starter
elasticsearchSecretName: secret-basic-auth
elasticsearchName: eks-fargate-starter-storage
jaegerName: eks-fargate-starter-observability
jaegerEndpoint: eks-fargate-starter-observability-collector.default:14250
otelName: eks-fargate-starter-otel 

grafana:
  enabled: true 
  adminUser: admin
  adminPassword: password
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://eks-prometheus-server.default.svc.cluster.local
        access: proxy
        isDefault: true
  persistence:
    type: pvc
    enabled: true
    storageClassName: standard-grafana
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    # annotations: {}
    finalizers:
      - kubernetes.io/pvc-protection
    # selectorLabels: {}
    ## Sub-directory of the PV to mount. Can be templated.
    # subPath: ""
    ## Name of an existing PVC. Can be templated.
    # existingClaim:
    ## Extra labels to apply to a PVC.
    extraPvcLabels: {}

    ## If persistence is not enabled, this allows to mount the
    ## local storage in-memory to improve performance
    ##
    inMemory:
      enabled: false
      ## The maximum usage on memory medium EmptyDir would be
      ## the minimum value between the SizeLimit specified
      ## here and the sum of memory limits of all containers in a pod
      ##
      # sizeLimit: 300Mi
  aws:
    enableStorage: true
    efs:
        fileSystemId: fs-05a5c065a9b2b8f34
        accessPointId: fsap-0dfb3865fa0081287      

prometheus:
  enabled: true
  fullnameOverride: eks-fargate-starter-prometheus
  aws:
    enableStorage: true 
    prometheusServer:
      efs:
        fileSystemId: fs-0ff243349915305fa
        accessPointId: fsap-06ca4a41475dc13d6
    prometheusAlertManager:
      efs:
        fileSystemId: fs-0eaf7a3c5f5abe044
        accessPointId: fsap-063383cf239e3ee7f

fluent-bit:
  fullnameOverride: eks-fargate-logging
  es_host_logging: eks-fargate-starter-storage-es-http.default
  eck-kibana:
    elasticsearchRefName: eks-fargate-starter-storage
    fullnameOverride: eks-fargate-visualisation
    eck-elasticsearch:
      storageSize: 10Gi 
      storageClassName: efs-sc
      aws:
        enableStorage: true
        efs:
          fileSystemId: fs-0a4285944e86d3698
          accessPointId: fsap-0480ddb3ac27e5188
      nodeSets:
      - name: default
        count: 1
        config:
          node.data: true
          node.ingest: true
          node.master: true
          node.store.allow_mmap: false
        count: 1
        name: default  
        podTemplate:
          spec:
            containers:
            - name: elasticsearch
              volumeMounts:
              - name: elasticsearch-data
                mountPath: /usr/share/elasticsearch/data
                readOnly: false
              resources:
                requests:
                  cpu: 2
                limits:
                  memory: 10Gi
        volumeClaimTemplates:
         - metadata:
             name: elasticsearch-data
           spec:
             accessModes:
               - ReadWriteMany
             resources:
               requests:
                 storage: 10Gi
             storageClassName: efs-sc
      fullnameOverride: eks-fargate-starter-storage
      username: wednesday-solutions
      password: password123
      cert-manager:
        createCustomResource: true